### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by TamalSaha** [ngaut/gearmand#11]
Hi,
We are interested in using this server in production. There has been no update to the code for a while. We wonder if this project is abandoned. Also, do you mind adding a LICENSE file directly to this repo?

Thanks.

**Comment by TamalSaha** [comment]
FWIW, we are further developing gearmand here: https://github.com/appscode/g2

**Comment by ngaut** [comment]
@TamalSaha This is a toy project for fun. It's not production ready. I'd happy to add a Apache 2 license file if you need.

**Comment by TamalSaha** [comment]
@ngaut adding a license will be great. Also, if you remember of the top of your head, what needs to be fixed to use it in production?

**Comment by ngaut** [comment]
@TamalSaha
I just added a license file. I can't really remember, i guess i forgot to add some limits, such as:
queue max length limit


Happy hacking!

**Comment by tamalsaha** [comment]
Thank you @ngaut !
